// Types and helpers for ADR 0001: dailies are pre-generated offline and
// published as immutable static JSON at /daily/<YYYY-MM-DD>.json.

export type DailySize = 6 | 8 | 12;

export const DAILY_SIZES: DailySize[] = [6, 8, 12];

export type DailyPuzzle = {
  size: DailySize;
  /** Provenance only, per the ADR. Not used by the client. A u64, so a decimal string (not a number) to keep full precision. */
  seed: string;
  puzzle: string;
  solutionSha256: string;
};

export type DailyFile = {
  version: number;
  date: string;
  generator: string;
  puzzles: DailyPuzzle[];
};

/** Today's date at the UTC day boundary, as `YYYY-MM-DD`. */
export const todayUtcDate = (): string => new Date().toISOString().slice(0, 10);

export const dailyFileUrl = (date: string): string => `/daily/${date}.json`;

/** Every published archive date, ascending. Regenerated by `scripts/generate-daily.ts`. */
export type DailyIndex = { dates: string[] };

export const dailyIndexUrl = (): string => "/daily/index.json";

/** Day 1 of the shared daily series (UTC), matching the first published archive. */
const DAILY_EPOCH_MS = Date.parse("2026-09-07T00:00:00Z");

/**
 * Daily puzzle index = whole UTC days since the shared epoch, +1. Launch day = 1.
 * Matches the `puzzleNumber` field of `com.tomplanche.atkuzu.result`.
 */
export const puzzleNumber = (date: string): number =>
  Math.round((Date.parse(`${date}T00:00:00Z`) - DAILY_EPOCH_MS) / 86_400_000) + 1;
